import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/Navbar";
import ClientWrapper from "@/components/ClientWrapper";
import ChatButton from "@/components/ChatBot/ChatButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CustomerLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ClientWrapper>
        <Navbar />
        {children}
      </ClientWrapper>
      <ChatButton />
    </>
  );
}
